apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: your-bot-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: your-bot
    spec:
      containers:
      - name: master
        image: gcr.io/your-project/your-bot:1.0.0
        env:
          - name: SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: slack-token
                key: token
          - name: DEBUG
            value: 'your-bot:*'
